apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic-system
spec:
  version: 7.10.0
  nodeSets:
  - name: default
    config:
      node.master: true
      node.data: true
      node.attr.attr_name: attr_value
      node.store.allow_mmap: false
    count: 1

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.10.0
  elasticsearchRef:
    name: elastic
  count: 1