apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  replicas: 1
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      resources:
        requests:
          storage: 1Gi
